### ISSUE TITLE
Review: ViewMoreEmissionsForHome and UserEmissionData

### ISSUE THREAD

**Issue by saitoshi** [shocking-development/shockingdevelopment#156]
## Overview

Please do a review on the following files listed before class next week Tuesday, April 27 11:30 AM (HST).

## Review Branch

The branches should be from master.

## Files to review
* [ViewMoreEmissionsForHome.jsx](https://github.com/shocking-development/shockingdevelopment/blob/master/app/imports/ui/pages/home/ViewMoreEmissionsForHome.jsx) 
* [UserEmissionData.jsx](https://github.com/shocking-development/shockingdevelopment/blob/master/app/imports/ui/components/defaultcharts/UserEmissionsData.jsx)

## Checklists

(Please edit the following list if necessary to indicate the actual checklists to be used.)

* [Architecture](../tree/master/checklists/architecture-checklist.md)
* [Design](../tree/master/checklists/design-checklist.md)
* [JS](../tree/master/checklists/js-checklist.md)
* [Meteor](../tree/master/checklists/meteor-checklist.md)
* [React](../tree/master/checklists/react-checklist.md)
* [Testing](../tree/master/checklists/testing-checklist.md)

## Due date
April 27, 11:30 AM (HST)

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by saitoshi** [comment]
### ViewMoreEmissionsForHome.jsx 

<b>JS-01: Name constructs appropriately.</b>
- line 13 const can be renamed to totalEmissionsRetrieved to match the name conventions wit other variables 
<b> Design </b>
- for line 45 is it possible to make the } in the previous line to avoid awkwardness 

### UserEmissionData.jsx
<b>JS-01: Name constructs appropriately.</b>
- line 45 if possible rename the const into finalResultMonths ?
- line 51 same as above: moneySpent ?

**Comment by kyraikeda** [comment]
### ViewMoreEmissionsForHome.jsx
**JS-01: Name constructs appropriately.**
The variable totalEmissionsretrieved does not follow camel case (line 13). Should be totalEmissionsRetrieved.

### UserEmissionsData.jsx 
**Design-05: Ensure comments are appropriate.**
Could use more comments explaining the parts of the code since it is a longer file.

**JS-01: Name constructs appropriately.**
Some variables do not follow camel case naming conventions like moneyspent (line 51) should be moneySpent and moneySavedtelework (line 89) should be moneySavedTelework.

**Comment by trey-sumida** [comment]
ViewMoreEmissionsForHome.jsx
Arch-02: Obey directory structure.
If rendered component is only part of a page it should be located in the components folder instead of the pages
Design-01: Can you refactor to reduce duplication?
Line 12-17: It may be possible to just return UserEmissionData('totalEmissions'); directly, eliminating the need for the const and return object
Design-05: Ensure comments are appropriate.
Line 79: Mentions ReactRouter however it does not seems to use it
JS-01: Name constructs appropriately.
Line 13: const doesn't follow camel case, should be totalEmissionsRetrieved

UserEmissionsData.jsx
Design-05: Ensure comments are appropriate.
Possibly provide more descriptive comments about what each function does/should be used for
JS-01: Name constructs appropriately.
Line 45: const doesn't follow camel case, should be finalResultMonths
Line 51: const doesn't follow camel case, should be moneySpent
Line 239-244: variables don't follow camel case, should start with lower case letter
Line 295: variable doesn't follow camel case, should start with lower case letter
Line 297: variable doesn't follow camel case, should start with lower case letter
Line 388-404: variables don't follow camel case
Line 416: variable doesn't follow camel case, should be personTransportation

**Comment by alohajerome** [comment]
ViewMoreEmissionsForHome.jsx:
Design-05: Ensure comments are appropriate - Line 79: Unnecessary comment
JS-01: Name Constructs Appropriately - Line 13: should be totalEmissionsRetrieved

UserEmissionsData.jsx:
JS-01: Name Constructs Appropriately - Variable names should all follow camel case, no matter what.

**Comment by mkirts** [comment]
ViewMoreEmissionsForHome.jsx:
- Design-05: Ensure comments are appropriate
Unnecessary comment at Line 79

UserEmissionsData.jsx:
- Design-05: Ensure comments are appropriate
Because this is a longer file, it's probably best to have more comments.
- JS-01: Name constructs appropriately
Several variables should be changed to camel case

**Comment by christianjensenv** [comment]
### ViewMoreEmissionsForHome.jsx:

- Design 05: L79 Random comment
- Fix comments to be more descriptive
- JS 01: L13 camelcase

### UserEmissionsData.jsx:

- Design 05: Descriptive comments would help
- JS 01: L45, L51 needs to be camelcased properly

**Comment by CalianaFortin** [comment]
**ViewMoreEmissionsForHome.jsx**
Arch-02: Obey directory structure.
Should be in in components directory.
Design-01: Reduce duplication move commonly used code to a export file 
JS-01: Name constructs appropriately.


**UserEmissionsData.jsx**
Design-05: Ensure comments are appropriate.
Provide comments about each function
JS-01: Name constructs appropriately.

**Comment by jtmoka** [comment]
Design-05, ViewMoreEmissionsForHome.jsx: Add more comments.

**Comment by cammoore** [comment]
## ViewMoreEmissionsForHome.jsx

L49, 52 Can we create a const style for the styles?
L36, 75 Why wrap modal in a div?
L79 Comment is wrong.

## UserEmissionData.jsx

L28 Why not use User()?

L39 - 43 Why not use UserEmissionsData()?

L72 We could use finalResultMonths.forEach

L74 - 386 Can we use a switch instead of if - else if

The code in the else if looks very similar. Can we refactor it?
