### ISSUE TITLE
Review: Navbars

### ISSUE THREAD

**Issue by kyraikeda** [shocking-development/shockingdevelopment#28]
## Overview

For this review, we're going to take a look at the Navbar Home and Navbar Landing components.

## Review Branch

review-#5

## Files to review

* [NavBarHome.jsx](https://github.com/shocking-development/shockingdevelopment/blob/master/app/imports/ui/components/home/NavBarHome.jsx)
* [NavBarLanding.jsx](https://github.com/shocking-development/shockingdevelopment/blob/master/app/imports/ui/components/Landing/NavBarLanding.jsx)

## Checklists

(Please edit the following list if necessary to indicate the actual checklists to be used.)

* [Architecture](https://github.com/cammoore/campus-cravings/tree/master/checklists/architecture-checklist.md)
* [Design](https://github.com/cammoore/campus-cravings/tree/master/checklists/design-checklist.md)
* [JS](https://github.com/cammoore/campus-cravings/tree/master/checklists/js-checklist.md)

## Due date

Tuesday, February 16

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by trey-sumida** [comment]
NavBarLanding.jsx:
Design-05: Ensure comments are appropriate
This navbar is only used on the landing page but the comment says that it appears on top of every page. Also is not rendered by the App component.

NavBarHome.jsx:
JS-01: Name constructs appropriately
Consider changing the file name since this navbar is not only used on the home page.
Design-05: Ensure comments are appropriate
This navbar is not rendered by the App component.
Design-07: Ensure code is readable
Some in-line styling are defined as consts at the top while others are defined in the component. Might want to make them all consts so components are easier to read.

**Comment by saitoshi** [comment]
NavBarHome.jsx 
Design-05: Ensure comments are appropriate.
Design-07: Ensure code is readable.
There are certain areas where the code could be reorganized to be read better 
JS-01: Name constructs appropriately.
Maybe rename it so that the it is used 

NavBarLanding.jsx
Design-05: Ensure comments are appropriate.
Some areas could have comments 
Design-07: Ensure code is readable.

**Comment by kyraikeda** [comment]
### NavBarHome.jsx
**Design-05: Ensure comments are appropriate.**
More comments should be used throughout the code.

**JS-01: Name constructs appropriately.**
This navbar is not only used for the home page. Name should be changed to something more applicable.


### NavBarLanding.jsx
**Design-05: Ensure comments are appropriate.**
More comments should be used throughout the code.

**Arch-01: Obey file name conventions.**
Landing directory that NavBarLanding.jsx is in should be lowercase L, so it should be landing.

**Comment by mkirts** [comment]
NavBarHome.jsx:
Design-05: Ensure comments are appropriate
I'd recommend adding additional comments throughout the code whenever possible.

JS-01: Name constructs appropriately
Rename it to appropriately fit it's usage.

NavBarLanding.jsx

Design-05: Ensure comments are appropriate.
Ditto from the NavBarHome

**Comment by alohajerome** [comment]
NavBarHome.jsx:
Design-07: Ensure code is readable
Design-05: Ensure comments are appropriate - Comment how functions/classes work in the file

NavBarLanding.jsx: 
Design-07,Design-05: similar to NavBarHome.jsx

**Comment by CalianaFortin** [comment]
## NavBarLanding.jsx
### Arch-01: obey filename conventions 

- the directory "Landing" should be renamed to "landing"

### Design-05: Ensure comments are appropriate.

- Some comments that do not match with the file, should change some of them to be appropriate. 

## NavBarHome.jsx

### Design-08: Ensure code is DRY.

- The dropdown code style is repeated should make it a const style.

### JS-01: Name constructs appropriately.

- rename the file to be more appropriately

### Design-05: Ensure comments are appropriate.

- Some comments that do not match with the file, should change some of them to be appropriate.

**Comment by awongway** [comment]
NavBarHome.jsx
Design-05: Ensure comments are appropriate.
Design-07: Ensure code is readable.

NavBarLanding.jsx
Design-05: Ensure comments are appropriate.
Design-07: Ensure code is readable.
