### ISSUE TITLE
Review: NavBars 

### ISSUE THREAD

**Issue by saitoshi** [shocking-development/shockingdevelopment#48]
## Overview

For this review, we're going to take a look at the Navbar Main and Navbar Landing components.

## Review Branch

review-#5

## Files to review

* [NavBarMain.jsx](https://github.com/shocking-development/shockingdevelopment/blob/master/app/imports/ui/components/main-navbar/NavBarMain.jsx)
* [NavBarLanding.jsx](https://github.com/shocking-development/shockingdevelopment/blob/master/app/imports/ui/components/landing/NavBarLanding.jsx)

## Checklists

(Please edit the following list if necessary to indicate the actual checklists to be used.)

* [Architecture](../tree/master/checklists/architecture-checklist.md)
* [Design](../tree/master/checklists/design-checklist.md)
* [JS](../tree/master/checklists/js-checklist.md)

## Due date

March 1, 2021

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by CalianaFortin** [comment]
### NavbarMain.jsx 
JS-01: Name constructs appropriately.

- Line 76 the name "NavBar2Containter" does not match the class name. It should be something like NavBarMainContainer.
- The name for the userstyling could be more descriptive. 

### NavBarLanding.jsx

Design-09: Ensure reusable code is exported or made available in the appropriate place.

- Some of the css styles should be places in the style sheet, so it is made available to edit later when trying to fix the styling for mobile.

JS-01: Name constructs appropriately.

- Line 76 the name "NavBar2Containter" does not match the class name. It should be something like NavBarLandingContainer.

**Comment by saitoshi** [comment]
NavBarHome.jsx
Design-05: Ensure comments are appropriate.
Design-07: Ensure code is readable.
There are certain areas where the code could be reorganized to be read better
JS-01: Name constructs appropriately.
Maybe rename it so that the it is used

NavBarLanding.jsx
Design-05: Ensure comments are appropriate.
Some areas could have comments
Design-07: Ensure code is readable.

**Comment by trey-sumida** [comment]
NavBarLanding.jsx:
Design-05: Ensure comments are appropriate
This navbar is only used on the landing page but the comment says that it appears on top of every page. Also is not rendered by the App component.

NavBarHome.jsx:
JS-01: Name constructs appropriately
Consider changing the file name since this navbar is not only used on the home page.
Design-05: Ensure comments are appropriate
This navbar is not rendered by the App component.
Design-07: Ensure code is readable
Some in-line styling are defined as consts at the top while others are defined in the component. Might want to make them all consts so components are easier to read.

**Comment by kyraikeda** [comment]
### NavBarMain.jsx
**Design-05: Ensure comments are appropriate.**
More comments should be used throughout the code.

**Design-09: Ensure reusable code is exported or made available in the appropriate place.**
Stylings like navbarVerticle and userstyling could be placed in the css style sheet.


### NavBarLanding.jsx
**Design-05: Ensure comments are appropriate.**
More comments should be used throughout the code.

**Design-09: Ensure reusable code is exported or made available in the appropriate place.**
Stylings like menuStyle, loginButton, and logo could be placed in the css style sheet.

**Comment by jtmoka** [comment]
NavBarMain.jsx
Design-05: Too few.
I do not see any other errors.

**Comment by trey-sumida** [comment]
NavBarLanding.jsx:
JS-01: Name constructs appropriately
Line 76 NavBar2Container could be changed to NavBarLandingContainer to be more consistent with file name
Design-09: Ensure reusable code is exported or made available in the appropriate place
loginButton and logo styling could be placed in stylesheet so that other files that use buttons/logo can consider using the same styling
NavBarMain.jsx:
JS-01: Name constructs appropriately
Line 95 NavBar2Container could be changed to NavBarMainContainer to be more consistent with file name

**Comment by awongway** [comment]
NavBarMain.jsx
Design-05: Ensure comments are appropriate.
Design-07: Ensure code is readable.
JS-01: Name constructs appropriately.

NavBarLanding.jsx
Design-05: Ensure comments are appropriate.
Design-07: Ensure code is readable.

**Comment by mkirts** [comment]
NavBarMain.jsx
JS-01: Name constructs appropriately
Line 95, you could change the name NavBar2Container to be consistent with the file name

Design-07: Ensure code is readable
There are portions where the code can be organized

NavBarLanding.jsx
JS-01: Name constructs appropriately
Line 76, ditto as in NavBarMain.jsx

**Comment by alohajerome** [comment]
NavBarMain.jsx:
Design-07: Ensure code is readable, comments on Menu Items?

NavBarLanding.jsx:
Design-09: Ensure Reusable code is exported or made available in the appropriate place, constants with css style can actually be placed in style.css

**Comment by cammoore** [comment]
NavBarMain.jsx

React-09: L13 prefer function since doesn't have state.

JS-08: L15, 94, 99 replace /** with //

ESLint: L38 can't we add a key to the menu?

NavBarLanding.jsx

React-09: L13 prefer function since doesn't have state.

JS-08: comments
