### ISSUE TITLE
Review: Data Component on the Home Page 

### ISSUE THREAD

**Issue by saitoshi** [shocking-development/shockingdevelopment#54]
(Delete all text in parentheses when filling out this template, including this text.)

## Overview

(Provide an introduction to this review. What are the goals? What should reviewers keep in mind as they do it?)

## Review Branch

(Please indicate the review branch here. It should be named review-xxx, where xxx is this issue number.)

## Files to review

(Please list the files to be reviewed here. It would be great to provide the URL to each file in the review branch.)

*[ Datapage.jsx]( https://github.com/shocking-development/shockingdevelopment/blob/master/app/imports/ui/pages/Datapage.jsx)

## Checklists

(Please edit the following list if necessary to indicate the actual checklists to be used.)

* [Architecture](../tree/master/checklists/architecture-checklist.md)
* [Design](../tree/master/checklists/design-checklist.md)
* [JS](../tree/master/checklists/js-checklist.md)
* [Meteor](../tree/master/checklists/meteor-checklist.md)
* [React](../tree/master/checklists/react-checklist.md)
* [Testing](../tree/master/checklists/testing-checklist.md)

## Due date

(Indicate when the review meeting is scheduled to occur.)

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by saitoshi** [comment]
### Arch-01: Obey file name conventions.
The file should be name as DataPage to observe the camel case standards.

### Design-05: Ensure comments are appropriate.
Probably could add comments to describe what the styling component does?

### JS-01: Name constructs appropriately.
The naming of the styles could be more consistent.

**Comment by trey-sumida** [comment]
Arch-01: Obey file name conventions.
Name of file should be ‘DataPage’ instead of ‘Datapage’
Design-09: Ensure reusable code is exported or made available in the appropriate place.
Consider moving styling to the stylesheet to reduce code and make it more readable
JS-01: Name constructs appropriately.
If planning on leaving the styling, consts defined on lines 24, 30, 37, 45, 57, 69, 80 need to be named appropriately using camel case with the first word starting with a lowercase

Side note: consider converting to a functional component as there is no state

**Comment by mkirts** [comment]
Arch-01: Obey file name convenctions
Change the file name from 'Datapage.jsx' to 'DataPage.jsx'.

JS-01: Name constructs appropriately
Naming styles could be a little more consistent; consider using camelcase (i.e. line 69: dataTableDivstyling  -> dataTableDivStyling)

**Comment by kyraikeda** [comment]
### Arch-01: Obey file name conventions
File name should be 'DataPage.jsx'.

### Design-09: Ensure reusable code is exported or made available in the appropriate place.
You could move the styling code (Lines 18 to 88) to the style.css file.

### JS-08: Use JSDoc comments appropriately.
Line 17 should use // instead of /**.

### JS-01: Name constructs appropriately.
The styling variables in lines 24, 30, 37, 45, 57, 69, 80 should adhere to camel case.

**Comment by alohajerome** [comment]
Arch-01: Obey file name conventions - Change File name to be "DataPage.jsx"
JS-01: Name constructs appropriately - Fix const variable names to follow camel case rule

**Comment by awongway** [comment]
Arch-01: Obey file name conventions
- File name to be "DataPage.jsx"
JS-01: Name constructs appropriately
- Consistent naming styles

**Comment by CalianaFortin** [comment]
Arch-01: Obey file name conventions
File name should be renamed to 'DataPage.jsx'.

Design-09: Ensure reusable code is exported or made available in the appropriate place.
The styling should be moved to the style.css file.

JS-01: Name constructs appropriately.
The styling variables in lines should be camel case.

JS-08: Use JSDoc comments appropriately.
Should use // instead of /**.

(The component should also be changed to a pure function since there is no state.)

**Comment by jtmoka** [comment]
Arch-01: chang nome to DataPage.
