### ISSUE TITLE
Review: Go To Data Page Bar graph 

### ISSUE THREAD

**Issue by saitoshi** [shocking-development/shockingdevelopment#78]
## Overview

Please work on reviewing the Go To Saving Pages.

## Files to review

* [DatapageBargraph.jsx](https://github.com/shocking-development/shockingdevelopment/blob/master/app/imports/ui/components/defaultcharts/DataPageBarGraph.jsx)

## Checklists

(Please edit the following list if necessary to indicate the actual checklists to be used.)

* [Architecture](../tree/master/checklists/architecture-checklist.md)
* [Design](../tree/master/checklists/design-checklist.md)
* [JS](../tree/master/checklists/js-checklist.md)
* [Meteor](../tree/master/checklists/meteor-checklist.md)
* [React](../tree/master/checklists/react-checklist.md)
* [Testing](../tree/master/checklists/testing-checklist.md)

## Due date

Please work on this before class on Tuesday. 

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by saitoshi** [comment]
* Design-04: Eliminate large comment blocks.
Is it possible to condense the comments from line 33 to 35
* Design-03: Eliminate dead code.
On the top can you remove the import CalculateCO2 since it is not being used?

**Comment by trey-sumida** [comment]
**Design-05: Ensure comments are appropriate.**
Line 9 uses /** but should consider using /*
**ESLINT-01: No errors, avoid warnings.**
Line 6 is it possible to not use disable eslint comment?

**Comment by alohajerome** [comment]
-Design-05: Ensure comments are appropriate. <- Eliminate the "how comments"
Lines 24-26 is too detailed. Unnecessary to explain the how. 
-Other than that, I didn't find anything wrong with the jsx file.

**Comment by christianjensenv** [comment]
**Design-04:** Line 24 - Line 26, Can we shorten the comment and make it more concise. 
**ESLINT-01:** Line 6 - Maybe find a way to remove the eslint disable.
Lines 27:30, 56:36, 77:27, change from double quotes to single quotes.
**Minor changes that the user might pick up:**
Line 15:47 - Cummulative -> Cumulative,
Line 82:102 - todays -> today's.
_Not too much wrong with this file._

**Comment by CalianaFortin** [comment]
**JS-08: Use JSDoc comments appropriately.**
- remove the comment on line 7 or edit it to make it appropriate for the file
**Arch-03: Are new directories consistent with existing directories?**
- Fix the file name to be more descriptive of what kind of info/data the directory holds
**Design-05: Ensure comments are appropriate.**
-After these problems have been addressed please remove these comments

**Comment by jtmoka** [comment]
Design-04: The comments lines 22-25 should be reduced
Design-01: Code repeats for all bar graphs

**Comment by kyraikeda** [comment]
### Design-04: Eliminate large comment blocks.
Shorten the comment section from lines 22-25

### Design-05: Ensure comments are appropriate.
Line 7 should use /* instead of /**

### Other comments:
Check for spelling, like in line 13 "Cummulative" should be "Cumulative"
Use consistent capitalization in lines 21, 29, 33

**Comment by mkirts** [comment]
Design-04: Eliminate Large Comment blocks
Short the amount of comments in lines 22-25

Design-05: Ensure comments are appropriate.
Use /** instead of /* on line 7

Arch-01: Obey file name conventions:
Name of the file should be in camelcase (i.e. dataPageBarGraph.jsx instead of DatapageBargraph.jsx)

Not a whole lot of things wrong with this file. There are some minor typos, but they don't impede on the design reviews
